---
- name: Fetch secret value
  ansible.builtin.command:
    cmd: aws secretsmanager get-secret-value --secret-id {{ secret_arn }} --query SecretString --output text
  register: secret_value

- name: Parse secret value
  ansible.builtin.set_fact:
    secret_json: "{{ secret_value.stdout | from_json }}"

- name: Set database credentials
  ansible.builtin.set_fact:
    database_username: "{{ secret_json.username }}"
    database_password: "{{ secret_json.password }}"
    database_endpoint: "{{ secret_json.endpoint }}"