FROM node:20-alpine

RUN mkdir -p ./usr/src/cyf-hotel/server

WORKDIR /usr/src/cyf-hotel/server

COPY ./server/package*.json ./

RUN npm ci

COPY ./server .

# ARG SERVER_PORT
# ARG DATABASE_URL
# ENV SERVER_PORT=$SERVER_PORT
# ENV DATABASE_URL=$DATABASE_URL

EXPOSE 4000

CMD ["npm", "start"]
