version: '3'
services:
  backend:
    image: susanssky/devops:cyf-hotel-backend
    restart: always
    ports:
      - 4000:4000
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DATABASE_URL=${DATABASE_URL}
