global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "nodejs_app"
    static_configs:
      - targets: ["cyf-hotel-backend:4000"]
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "yace"
    static_configs:
      - targets: ["yace:5000"]
