---
- name: Download AWS CLI v2
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip

- name: Unzip AWS CLI package
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: yes

- name: Install AWS CLI
  command: /tmp/aws/install --update --install-dir /usr/local/aws-cli --bin-dir /usr/local/bin
  args:
    creates: /usr/local/bin/aws

- name: Clean up downloaded files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/awscliv2.zip
    - /tmp/aws

- name: Verify AWS CLI installation
  command: aws --version
  register: aws_version

- name: Debug AWS CLI version
  debug:
    msg: "{{ aws_version.stdout }}"