---
- name: Install packages and aws cli
  hosts: aws_ec2
  become: yes
  roles:
    - install_packages
    - aws_cli

- name: Get values from secret manager and copy some files
  hosts: aws_ec2
  roles:
    - secret
    - copy_files
  vars:
    docker_compose_src: ../docker-compose-week5-prom-glp.yaml
    docker_compose_dest: docker-compose-week5-prom-glp.yaml

- name: Set up docker
  hosts: aws_ec2
  become: yes
  roles:
    - docker_job
  vars:
    docker_compose_src: ../docker-compose-week5-prom-glp.yaml
    docker_compose_dest: docker-compose-week5-prom-glp.yaml