apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: database-secrets
    creationPolicy: Owner
  data: 
  - secretKey: db_name
    remoteRef:
      key: db-name
  - secretKey: db_user
    remoteRef:
      key: db-user
  - secretKey: db_pass
    remoteRef:
      key: db-pass