# apply all ns
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: cloud-week6-cyf-hotel

# apiVersion: external-secrets.io/v1
# kind: SecretStore
# metadata:
#   name: gcp-store
#   namespace: default <--only apply this ns
# spec:
#   provider:
#     gcpsm:
#       projectID: cloud-week6-cyf-hotel