apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: myapp-source
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/susanssky/rebuild-cyf-hotel
  ref:
    branch: main
  secretRef:
    name: github-repo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: myapp
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: flux-prod
  sourceRef:
    kind: GitRepository
    name: myapp-source
  path: "./manifest-k8s"
  prune: true
  timeout: 1m
