{
 "title": "custom dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RDS CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_average{dimension_DBInstanceIdentifier=\"cloud-week5-hotel-db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EC2 CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (HTTP Request Duration)",
   "type": "timeseries",
   "description": "Measure the latency of HTTP requests to identify performance bottlenecks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, path))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RDS up or down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "EC2 Up or Down",
   "type": "stat",
   "description": "Monitor the status of virtual machines hosting the application and database using Node Exporter.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Active Connections ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{datname=\"postgres\", state=\"active\"}) by (datname)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EC2 Availability (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{job=\"node_exporter\"}[7d]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EC2 Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of HTTP Requests",
   "type": "timeseries",
   "description": "Monitor the rate of HTTP requests to the backend application to understand traffic patterns and detect anomalies.",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(http_requests_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "EC2 Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database I/O Time:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_blk_read_time{datname=\"postgres\"}[5m])) / 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}