name: Week5 Coursework with Prometheus, Grafana, Loki, Pormtail
permissions:
  id-token: write
  contents: read
# on: push
on:
  project:
    types: deleted
jobs:
  deploy:
    uses: ./.github/workflows/reusable-week5.yaml
    with:
      ansible_playbook: ec2-prom-glp.yaml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      EC2_PUBLIC_KEY: ${{ secrets.EC2_PUBLIC_KEY }}
      EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
