name: Week5 Coursewrok
on: push
permissions: # because use role-to-assume to login aws
  id-token: write
  contents: read
# on:
#   project:
#     types: deleted
jobs:
  RDS_EC2:
    runs-on: ubuntu-latest
    outputs:
      rds-endpoint: ${{ steps.rds-ec2-outputs.outputs.RDS_ENDPOINT }}
      ec2-ip: ${{ steps.rds-ec2-outputs.outputs.EC2_IP }}
      ec2-id: ${{ steps.rds-ec2-outputs.outputs.EC2_ID }}
      ec2_private_key: ${{ steps.rds-ec2-outputs.outputs.EC2_PRIVATE_KEY }}
      key-name: ${{ steps.rds-ec2-outputs.outputs.KEY_NAME }}
      ec2_security-group-id: ${{ steps.rds-ec2-outputs.outputs.EC2_SG_ID }}
      vpc-id: ${{ steps.rds-ec2-outputs.outputs.VPC_ID }}
      rds-identifier: ${{ steps.rds-ec2-outputs.outputs.RDS_IDENTIFIER }}
      public-subnet-ids: ${{ steps.rds-ec2-outputs.outputs.PUBLIC_SUBNET_IDS }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false # for get the terraform output value
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::503447358475:role/aws-gh-action
          aws-region: eu-west-2
      - name: Terraform command
        working-directory: ./terraform-week5/1-rds-ec2
        run: |
          terraform init
          terraform fmt -check
          terraform apply -auto-approve -var "database_username=${{ secrets.POSTGRES_USER }}" -var "database_password=${{ secrets.POSTGRES_PASSWORD }}" -var "docker_pw=${{ secrets.DOCKER_PW }}"
      - name: save the outputs value from tf to the outputs in this job
        id: rds-ec2-outputs
        working-directory: ./terraform-week5/1-rds-ec2
        run: |
          echo "RDS_ENDPOINT=$(terraform output -raw rds_endpoint)" >> $GITHUB_OUTPUT
          echo "EC2_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_OUTPUT
          echo "EC2_ID=$(terraform output -raw ec2_id)" >> $GITHUB_OUTPUT
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "EC2_PRIVATE_KEY<<$EOF" >> $GITHUB_OUTPUT
          echo "$(terraform output -raw ec2_private_key)" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
          echo "KEY_NAME=$(terraform output -raw key_name)" >> $GITHUB_OUTPUT
          echo "EC2_SG_ID=$(terraform output -raw ec2_security_group_id)" >> $GITHUB_OUTPUT
          echo "VPC_ID=$(terraform output -raw vpc_id)" >> $GITHUB_OUTPUT
          echo "PUBLIC_SUBNET_IDS=$(terraform output -json public_subnet_id)" >> $GITHUB_OUTPUT
          echo "RDS_IDENTIFIER=$(terraform output -raw rds_identifier)" >> $GITHUB_OUTPUT

  set-up-database-backend:
    needs: RDS_EC2
    runs-on: ubuntu-latest
    env:
      EC2_ID: ${{ needs.RDS_EC2.outputs.ec2-id }}
      EC2_IP: ${{ needs.RDS_EC2.outputs.ec2-ip }}
      PRIVATE_KEY: ${{ needs.RDS_EC2.outputs.ec2_private_key }}
      USER_NAME: ${{ secrets.EC2_USERNAME }}

      RDS_ENDPOINT: ${{  needs.RDS_EC2.outputs.rds-endpoint }}
      RDS_USER: ${{ secrets.POSTGRES_USER }}
      RDS_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      SERVER_PORT: 4000
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        if: steps.filter.outputs.backend == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push backend image to hub if there are any updadte in backend
        if: steps.filter.outputs.backend == 'true'
        run: |
          docker build -f Dockerfile.backend -t susanssky/devops:cyf-hotel-backend .
          docker push susanssky/devops:cyf-hotel-backend
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::503447358475:role/aws-gh-action
          aws-region: eu-west-2
      - name: Login with ssh & Import SQL Data & Docker-compose up
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          mkdir -p ~/.ssh
          cat >>~/.ssh/config << EOF
          Host ec2
            HostName $EC2_IP
            User $USER_NAME
            IdentityFile private_key
            StrictHostKeyChecking no
          EOF
          scp "./database/seeding.sql" ec2:./
          ssh ec2 "sudo -u postgres -i psql postgresql://${RDS_USER}:${RDS_PASSWORD}@$RDS_ENDPOINT < seeding.sql"
          ssh ec2 "rm seeding.sql"
          scp "./docker-compose-week4.yaml" ec2:./
          ssh ec2 "echo "SERVER_PORT=${SERVER_PORT}" > .env && \
          echo "DATABASE_URL=postgres://${RDS_USER}:${RDS_PASSWORD}@${RDS_ENDPOINT}/" >> .env && \
          sudo docker login && \
          sudo docker-compose -f docker-compose-week4.yaml pull && \
          sudo docker-compose -f docker-compose-week4.yaml up -d && sudo docker image prune -a -f"

  AS_LB_CW:
    runs-on: ubuntu-latest
    needs: [RDS_EC2, set-up-database-backend]
    env:
      RDS_IDENTIFIER: ${{ needs.RDS_EC2.outputs.rds-identifier }}
      EC2_ID: ${{ needs.RDS_EC2.outputs.ec2-id }}
      KEY_NAME: ${{ needs.RDS_EC2.outputs.key-name }}
      EC2_SG_ID: ${{ needs.RDS_EC2.outputs.ec2_security-group-id }}
      VPC_ID: ${{ needs.RDS_EC2.outputs.vpc-id }}
      PUBLIC_SUBNET_IDS: ${{ needs.RDS_EC2.outputs.public-subnet-ids }}

    outputs:
      server_url: ${{ steps.as-lb-cw-outputs.outputs.LB_DNS_NAME }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false # for get the terraform output value
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::503447358475:role/aws-gh-action
          aws-region: eu-west-2
      - name: Terraform command
        working-directory: ./terraform-week5/2-as-lb-cw
        run: |
          echo $PUBLIC_SUBNET_IDS
          terraform init
          terraform fmt -check
          terraform apply -auto-approve -var "from_previous_workflow_ec2_id=$EC2_ID" -var "from_previous_workflow_key_name=$KEY_NAME" -var "from_previous_workflow__security_group_id=$EC2_SG_ID" -var "from_previous_workflow_vpc_id=$VPC_ID" -var "from_previous_workflow_public_subnet_ids=$PUBLIC_SUBNET_IDS" -var "from_previous_workflow_rds_identifier=$RDS_IDENTIFIER"
      # - name: stop instances
      #   run: aws ec2 stop-instances --instance-ids $EC2_ID
      - name: save the outputs value from tf to the outputs in this job
        id: as-lb-cw-outputs
        working-directory: ./terraform-week5/2-as-lb-cw
        run: echo "LB_DNS_NAME=$(terraform output -raw lb-dns-name)" >> $GITHUB_OUTPUT

  set-up-frontend-and-run-tf:
    needs: [AS_LB_CW]
    runs-on: ubuntu-latest
    env:
      SERVER_URL: ${{ needs.AS_LB_CW.outputs.server_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Create env file
        working-directory: ./client
        run: |
          echo "VITE_SERVER_URL=http://${SERVER_URL}" > .env
          cat .env
      - name: build static frontend website
        working-directory: ./client
        run: |
          npm ci
          npm run build
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::503447358475:role/aws-gh-action
          aws-region: eu-west-2
      - name: Terraform command
        working-directory: ./terraform-week5/3-s3
        run: |
          terraform init
          terraform fmt -check
          terraform apply -auto-approve
