---
- name: Update apt cache and install the packages
  ansible.builtin.apt:
    name:
      - postgresql
      - docker.io
      - docker-compose-v2
      - unzip
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: yes